### ISSUE TITLE
Investigate why zipline is hanging

### ISSUE THREAD

**Issue by kubode** [kubode/conference-app-2022#3]
Part of https://github.com/DroidKaigi/conference-app-2022/issues/250

**Comment by kubode** [comment]
# Logcat

```
Zipline modifier error
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 100 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by kubode** [comment]
# Where are `withTimeout(100)` used

https://github.com/kubode/conference-app-2022/blob/9831942f52a0ad275a25525cbebb9eda5ddfb832/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/SessionsViewModel.kt#L51-L58

https://github.com/kubode/conference-app-2022/blob/9831942f52a0ad275a25525cbebb9eda5ddfb832/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/SearchViewModel.kt#L43-L50

**Comment by kubode** [comment]
# Increasing the timeout solves the issue?

No.

It hangs in the following lambda.

https://github.com/kubode/conference-app-2022/blob/9831942f52a0ad275a25525cbebb9eda5ddfb832/core-zipline/src/androidMain/kotlin/io/github/droidkaigi/confsched2022/zipline/SessionsZipline.kt#L95

**Comment by kubode** [comment]
# Why `modifier.modify()` is hanging?

Because `zipline` instance is closed.

`Zipline.close()` documentation says:

> Release resources held by this instance. It is an error to do any of the following after calling close:
> Call `take` or `bind`.
> Accessing `quickJs`.
> Accessing the objects returned from `take`.


https://github.com/kubode/conference-app-2022/blob/9831942f52a0ad275a25525cbebb9eda5ddfb832/core-zipline/src/androidMain/kotlin/io/github/droidkaigi/confsched2022/zipline/SessionsZipline.kt#L97-L100

# How to solve
So we can solve this issue by closing the zipline instance at the right time.

**Comment by kubode** [comment]
# How to verify

See https://github.com/DroidKaigi/conference-app-2022/issues/250#issuecomment-1246629260

**Comment by kubode** [comment]
# `zipline.close()` problem

`zipline.close()` releases zipline resources.
However, if you close it when there is a running JS in the zipline instance, it will crash with an assertion exception.

https://github.com/cashapp/zipline/blob/721b723b616d77d47b82a647d4a5ae74e1788118/zipline/src/engineMain/kotlin/app/cash/zipline/Zipline.kt#L66-L69

Execution of `modifier.modify(timetable)` takes 300ms even on Pixel 6 Pro, so the app crashes with the following log frequently when returning from the search screen.


```
FATAL EXCEPTION: Zipline
Process: io.github.droidkaigi.confsched2022.dev, PID: 32337
java.lang.IllegalStateException: Zipline closed
	at app.cash.zipline.Zipline$endpoint$1.call(Zipline.kt:67)
	at app.cash.zipline.internal.bridge.OutboundCallHandler.call(OutboundCallHandler.kt:57)
	at app.cash.zipline.internal.JsPlatform$Companion$Adapter$GeneratedOutboundService.runJob(platform.kt:37)
	at app.cash.zipline.internal.CoroutineEventLoop$DelayedJob$run$1.invokeSuspend(CoroutineEventLoop.kt:59)
	at app.cash.zipline.internal.CoroutineEventLoop$DelayedJob$run$1.invoke(Unknown Source:8)
	at app.cash.zipline.internal.CoroutineEventLoop$DelayedJob$run$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at app.cash.zipline.internal.CoroutineEventLoop$DelayedJob.run(CoroutineEventLoop.kt:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c294101, java.util.concurrent.Executors$FinalizableDelegatedExecutorService@7252ba6]
```

For this reason, I think it is better not to close the zipline instance.

**Comment by kubode** [comment]
# 📝 

JS execution time: 16ms
`modifier.modify` execution time: 300ms
